// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var apiEnvPoint = process.env.NEXT_PUBLIC_API_ENDPOINT;

var githubToken = process.env.NEXT_PUBLIC_GITHUB_TOKEN;

exports.apiEnvPoint = apiEnvPoint;
exports.githubToken = githubToken;
/* apiEnvPoint Not a pure module */
